### ISSUE TITLE
Kimidi is not compatible with macOS Catalina (10.15)

### ISSUE THREAD

**Issue by wiffbi** [wiffbi/Kimidi#1]
Kimidi is not running under macOS Catalina. It currently has a few dependencies that make it incompatible with macOS Catalina.

**Comment by NathanR-85** [comment]
Is it working well with Catalina since the update? Would love to know. Kimidi is a life saver :) 👍

**Comment by NathanR-85** [comment]
Following up on this... I think I need to upgrade to Catalina and *need* Kimidi (I don't think an alternative exists). Thank you

**Comment by wiffbi** [comment]
Yeah, sorry, this is fixed with #2 so I will close this. You can safely upgrade to Catalina! Yay!
